@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Система онлайн-открытия депозитов

Person(Client, "Клиент", "Физическое лицо, открывающее депозит через онлайн-каналы")
Person(BOManager, "Менеджер бэк-офиса", "Сотрудник банка, обрабатывающий заявки на депозиты")
Person(FOManager, "Менеджер фронт-офиса", "Сотрудник отделения банка")
Person(CCOperator, "Оператор кол-центра", "Сотрудник кол-центра, консультирующий клиентов")

System(DepositsSystem, "Система онлайн-открытия депозитов", "Предоставляет возможность открытия депозитов через онлайн-каналы")

System_Ext(Abs, "АБС", "Автоматизированная банковская система")
System_Ext(SmsGw, "СМС-шлюз", "Система отправки SMS-сообщений")
System_Ext(Telecom, "Телеком-оператор", "Внешний оператор связи")

Client --> DepositsSystem: Открывает депозит через\nонлайн-каналы
Client --> DepositsSystem: Просматривает актуальные\nи персональные ставки
Client --> DepositsSystem: Подтверждает операцию\nSMS-кодом

BOManager --> DepositsSystem: Обрабатывает заявки\nна открытие депозитов
FOManager --> DepositsSystem: Работает с клиентами\nв отделении (на будущее)
CCOperator --> DepositsSystem: Консультирует клиентов\nпо условиям депозитов

DepositsSystem --> Abs: Синхронизация данных\nо клиентах и счетах
DepositsSystem --> Abs: Передача информации\nоб открытых депозитах
DepositsSystem --> SmsGw: Отправка SMS-уведомлений\nи кодов подтверждения
SmsGw --> Telecom: Передача SMS-сообщений\nдля доставки клиентам

Abs --> DepositsSystem: Предоставляет данные\nо клиентах и счетах
SmsGw --> DepositsSystem: Подтверждение доставки\nSMS-сообщений

note right of Client
  <b>Каналы взаимодействия:</b>
  • Сайт банка
  • Интернет-банк
  • Мобильное приложение
  (в перспективе)
end note

note left of BOManager
  <b>Процесс:</b>
  Ручная обработка заявок
  с последующей автоматизацией
end note

note right of Abs
  Асинхронное взаимодействие
  через буфер обмена сообщениями
  для избежания прямой нагрузки
end note

@enduml
